32KHz Crystal
macchina/arduino-boards-sam pull request #27
Opened 2017-09-16 10:21 UTC by TDoust

Added functions to enable the use of the External 32KHz Crystal instead of the internal clock

2017-09-18 23:02 UTC, adamvoss requested changes
This PR includes a bunch of merge commits and all your previous PRs.  Ideally (in this case) it would only contain one commit containing the clock changes.  As is, I cannot easily identify which commit corresponds to the change for this PR (it appears to be missing actually this this PR the same as #25 was prior to my cleaning up the merge commits in that PR).

Could you do a force push to clean up the commits in this PR?  You will not be able to do this through the GitHub Desktop UI.

2017-09-20 00:43 UTC, adamvoss commented
@TDoust Thanks for the new commit!  Will you try your hand at rebasing it, or should I do it again?

2017-09-20 06:17 UTC, TDoust commented
Hi adam

Rebassing it probably is better if you do as I may screw it up more than it currently is

Still trying to get my head around having branches that are 6 commits ahead of pull request 19 say & then starting another branch because its not to be attached to the other commits & pull requests

I will get there in the end

 

 

Regards Tony Doust

 <mailto:t_doust@optusnet.com.au> t_doust@optusnet.com.au

+61 (0)413 207 336

 

From: Adam Voss [mailto:notifications@github.com] 
Sent: Wednesday, 20 September 2017 10:43 AM
To: macchina/arduino-boards-sam <arduino-boards-sam@noreply.github.com>
Cc: Tony Doust <t_doust@optusnet.com.au>; Mention <mention@noreply.github.com>
Subject: Re: [macchina/arduino-boards-sam] 32KHz Crystal (#27)

 

@TDoust <https://github.com/tdoust>  Thanks for the new commit! Will you try your hand at rebasing it, or should I do it again?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub <https://github.com/macchina/arduino-boards-sam/pull/27#issuecomment-330712729> , or mute the thread <https://github.com/notifications/unsubscribe-auth/ANWNoptxHWGSniJdpUlWRGkcaaXqT4tCks5skF-XgaJpZM4PZxxP> .  <https://github.com/notifications/beacon/ANWNouQVI3O4O0cvGN4WiBnW4iREZPY8ks5skF-XgaJpZM4PZxxP.gif>

2017-09-22 00:40 UTC, adamvoss approved these changes

2017-09-22 00:50 UTC, adamvoss commented on sam/variants/m2/variant.cpp
> +  while(!pmc_osc_is_ready_32kxtal());   // wait for the clock to be set
Will having this always enabled have any power-draw implications?

2017-09-22 00:58 UTC, TDoust commented
Hi adam

Having this always enabled will lower the power usage of the CPU according to the data sheet

 

 

Regards Tony Doust

 <mailto:t_doust@optusnet.com.au> t_doust@optusnet.com.au

+61 (0)413 207 336

 

From: Adam Voss [mailto:notifications@github.com] 
Sent: Friday, 22 September 2017 10:50 AM
To: macchina/arduino-boards-sam <arduino-boards-sam@noreply.github.com>
Cc: Tony Doust <t_doust@optusnet.com.au>; Mention <mention@noreply.github.com>
Subject: Re: [macchina/arduino-boards-sam] 32KHz Crystal (#27)

 

@adamvoss commented on this pull request.

  _____  

In sam/variants/m2/variant.cpp <https://github.com/macchina/arduino-boards-sam/pull/27#discussion_r140392234> :

> @@ -478,6 +478,10 @@ void init( void )
     g_APinDescription[PINS_CAN1].ulPin,
     g_APinDescription[PINS_CAN1].ulPinConfiguration);
 
+  // enable the use of the external 32Khz clock
+  pmc_switch_sclk_to_32kxtal(PMC_OSC_XTAL); // enable the external 32kHz crystal
+  while(!pmc_osc_is_ready_32kxtal());   // wait for the clock to be set

Will having this always enabled have any power-draw implications?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub <https://github.com/macchina/arduino-boards-sam/pull/27#pullrequestreview-64460403> , or mute the thread <https://github.com/notifications/unsubscribe-auth/ANWNor1GxQuekU0D91CHWgIjdrZ0JbXzks5skwQ-gaJpZM4PZxxP> .  <https://github.com/notifications/beacon/ANWNoqe-7qGxqa4j1tLfqmkD7Rvz0M7hks5skwQ-gaJpZM4PZxxP.gif>

2017-09-22 01:01 UTC, adamvoss commented
Alright, I'll just assume the CPU savings are greater than whatever draw is lost to the crystal giving us a net gain :+1:!

2017-09-22 01:02 UTC, merged

2017-09-22 01:57 UTC, TDoust commented
Adam

Sorry I should have added a little more information

As it stands now we are running the External slow clock & the internal slow clock by switching off the internal slow clock overall power consumption is reduced

According to the data sheet the internal RC slow clock is enabled by default & by utilising the external slow clock the processor current draw is reduced

Atmel Data sheet 16.4.2 Slow Clock Generator paragraph 2. The external crystal slow clock is more accurate than the internal RC oscillator. 27.4.2 Slow Clock Crystal Oscillator 

Am currently looking at possible further power reductions VDDCORE & what implications this will have & even if possible to implement. Still undesided if will persue further.

Last paragraph 16.4.3 Voltage Regulator Control/Backup Low Power Mode

 

 

 

Regards Tony Doust

 <mailto:t_doust@optusnet.com.au> t_doust@optusnet.com.au

+61 (0)413 207 336

 

From: Adam Voss [mailto:notifications@github.com] 
Sent: Friday, 22 September 2017 10:50 AM
To: macchina/arduino-boards-sam <arduino-boards-sam@noreply.github.com>
Cc: Tony Doust <t_doust@optusnet.com.au>; Mention <mention@noreply.github.com>
Subject: Re: [macchina/arduino-boards-sam] 32KHz Crystal (#27)

 

@adamvoss commented on this pull request.

  _____  

In sam/variants/m2/variant.cpp <https://github.com/macchina/arduino-boards-sam/pull/27#discussion_r140392234> :

> @@ -478,6 +478,10 @@ void init( void )
     g_APinDescription[PINS_CAN1].ulPin,
     g_APinDescription[PINS_CAN1].ulPinConfiguration);
 
+  // enable the use of the external 32Khz clock
+  pmc_switch_sclk_to_32kxtal(PMC_OSC_XTAL); // enable the external 32kHz crystal
+  while(!pmc_osc_is_ready_32kxtal());   // wait for the clock to be set

Will having this always enabled have any power-draw implications?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub <https://github.com/macchina/arduino-boards-sam/pull/27#pullrequestreview-64460403> , or mute the thread <https://github.com/notifications/unsubscribe-auth/ANWNor1GxQuekU0D91CHWgIjdrZ0JbXzks5skwQ-gaJpZM4PZxxP> .  <https://github.com/notifications/beacon/ANWNoqe-7qGxqa4j1tLfqmkD7Rvz0M7hks5skwQ-gaJpZM4PZxxP.gif>